---
- hosts: webserver
  gather_facts: false

  vars_files:
    - ./vars/vars.yml

  environment:
    APP_ENV: "{{ app_env }}"

  pre_tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
      tags:
        - install

  roles:
    - php-cli
    - { role: apache2, apache2_site_name: "{{ site_name }}", apache2_site_directory: "{{ project_dir }}/current/public", apache2_app_user: "{{ app_user }}" }
